server:
  port: 8080

logging:
  level:
    ROOT: INFO

spring:
  application:
    name: twitter-to-kafka-service
  profiles:
    active: twitter_to_kafka
  config:
    # This is the "Modern" way to link to the Config Server
    # Use 'optional:' so the app starts even if the server is down
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      # 'name' is still used to tell the server which files to look for
      name: config-client,config-client-twitter_to_kafka
      username: spring_cloud_user
      password: ${CONFIG_SERVER_PASSWORD}